SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DELETE FROM prefix_calendarista_availability;
DELETE FROM prefix_calendarista_availability_booked;
DELETE FROM prefix_calendarista_coupons;
DELETE FROM prefix_calendarista_error_log;
DELETE FROM prefix_calendarista_feeds;
DELETE FROM prefix_calendarista_formelement;
DELETE FROM prefix_calendarista_formelement_booked;
DELETE FROM prefix_calendarista_holidays;
DELETE FROM prefix_calendarista_map;
DELETE FROM prefix_calendarista_map_booked;
DELETE FROM prefix_calendarista_optional;
DELETE FROM prefix_calendarista_optional_group;
DELETE FROM prefix_calendarista_optionals_booked;
DELETE FROM prefix_calendarista_order;
DELETE FROM prefix_calendarista_place;
DELETE FROM prefix_calendarista_place_aggregate_cost;
DELETE FROM prefix_calendarista_project;
DELETE FROM prefix_calendarista_reminders;
DELETE FROM prefix_calendarista_roles;
DELETE FROM prefix_calendarista_settings;
DELETE FROM prefix_calendarista_staff;
DELETE FROM prefix_calendarista_staging;
DELETE FROM prefix_calendarista_string_resources;
DELETE FROM prefix_calendarista_style;
DELETE FROM prefix_calendarista_timeslot;
DELETE FROM prefix_calendarista_waypoint;
DELETE FROM prefix_calendarista_waypoint_booked;
DELETE FROM prefix_calendarista_season;
DELETE FROM prefix_calendarista_gdpr;
DELETE FROM prefix_calendarista_auth;
DELETE FROM prefix_calendarista_pricing_scheme;
DELETE FROM prefix_calendarista_dynamic_field;
DELETE FROM prefix_calendarista_dynamic_field_booked;
DELETE FROM prefix_calendarista_dynamic_field_pricing;
DELETE FROM prefix_calendarista_gcal;
DELETE FROM prefix_calendarista_gcal_profile;
DELETE FROM prefix_calendarista_tags;
DELETE FROM prefix_calendarista_tags_availability;
DELETE FROM prefix_calendarista_availability_day;
DELETE FROM prefix_calendarista_order_availability;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;