SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP TABLE IF EXISTS  prefix_calendarista_availability;
DROP TABLE IF EXISTS  prefix_calendarista_availability_booked;
DROP TABLE IF EXISTS  prefix_calendarista_coupons;
DROP TABLE IF EXISTS  prefix_calendarista_error_log;
DROP TABLE IF EXISTS  prefix_calendarista_feeds;
DROP TABLE IF EXISTS  prefix_calendarista_formelement;
DROP TABLE IF EXISTS  prefix_calendarista_formelement_booked;
DROP TABLE IF EXISTS  prefix_calendarista_holidays;
DROP TABLE IF EXISTS  prefix_calendarista_map;
DROP TABLE IF EXISTS  prefix_calendarista_map_booked;
DROP TABLE IF EXISTS  prefix_calendarista_optional;
DROP TABLE IF EXISTS  prefix_calendarista_optional_group;
DROP TABLE IF EXISTS  prefix_calendarista_optionals_booked;
DROP TABLE IF EXISTS  prefix_calendarista_order;
DROP TABLE IF EXISTS  prefix_calendarista_place;
DROP TABLE IF EXISTS  prefix_calendarista_place_aggregate_cost;
DROP TABLE IF EXISTS  prefix_calendarista_project;
DROP TABLE IF EXISTS  prefix_calendarista_reminders;
DROP TABLE IF EXISTS  prefix_calendarista_roles;
DROP TABLE IF EXISTS  prefix_calendarista_settings;
DROP TABLE IF EXISTS  prefix_calendarista_staff;
DROP TABLE IF EXISTS  prefix_calendarista_staging;
DROP TABLE IF EXISTS  prefix_calendarista_string_resources;
DROP TABLE IF EXISTS  prefix_calendarista_style;
DROP TABLE IF EXISTS  prefix_calendarista_timeslot;
DROP TABLE IF EXISTS  prefix_calendarista_waypoint;
DROP TABLE IF EXISTS  prefix_calendarista_waypoint_booked;
DROP TABLE IF EXISTS  prefix_calendarista_season;
DROP TABLE IF EXISTS  prefix_calendarista_gdpr;
DROP TABLE IF EXISTS  prefix_calendarista_auth;
DROP TABLE IF EXISTS  prefix_calendarista_pricing_scheme;
DROP TABLE IF EXISTS  prefix_calendarista_dynamic_field;
DROP TABLE IF EXISTS  prefix_calendarista_dynamic_field_booked;
DROP TABLE IF EXISTS  prefix_calendarista_dynamic_field_pricing;
DROP TABLE IF EXISTS  prefix_calendarista_gcal;
DROP TABLE IF EXISTS  prefix_calendarista_gcal_profile;
DROP TABLE IF EXISTS prefix_calendarista_tags;
DROP TABLE IF EXISTS prefix_calendarista_tags_availability;
DROP TABLE IF EXISTS prefix_calendarista_availability_day;
DROP TABLE IF EXISTS prefix_calendarista_order_availability;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
