<?php
class Calendarista_EmailType{
	const MASTER_TEMPLATE = 0;
	const NEW_BOOKING_RECEIVED = 1;
	const BOOKING_RECEIVED_SUCCESS = 2;
	const BOOKING_CONFIRMATION = 3;
	const BOOKING_CANCELLED = 4;
	const BOOKING_REMINDER = 5;
	const BOOKING_PAYMENT_RECEVIED = 6;
	const COUPON = 7;
	const PAYMENT_REQUIRED = 8;
	const BOOKING_HAS_CHANGED = 9;
	const GDPR = 10;
	const BOOKING_CANCELLED_ALERT = 11;
	const APPOINTMENT_OUT_OF_STOCK = 12;
	const GOOGLE_CALENDAR_AUTHENTICATION_FAILURE = 13;
	const BOOKING_THANKYOU_REMINDER = 14;
}
?>